---
abstract: 'A module for merging hierarchies using the C3 algorithm'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
  - 'Brandon L. Black <blblack@gmail.com>'
build_requires:
  Test::More: '0.47'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.50, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Algorithm-C3
no_index:
  directory:
    - t
    - xt
requires:
  Carp: '0.01'
  perl: '5.006'
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Algorithm-C3
  license: http://dev.perl.org/licenses/
  repository: https://github.com/moose/Algorithm-C3.git
version: '0.11'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
x_static_install: 1
